source: src
destination: html
url: https://haroldmooiman.github.io
enforce_ssl: haroldmooiman.github.io
permalink             : /articles/:title/
include               : ["_pages"]

compress_html:
  clippings           : all
  comments            : ["<!-- ", " -->"]
  endings             : all
  blanklines          : false

title: Jimi's zooi
